<a href="https://colab.research.google.com/github/Greg-Vincent0711/Learning-Pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Gregory Vincent

In [ ]:
import torch

In [ ]:
# Intro to tensors
# tensor - way to represent data mathematically
# tensors can represent multiple different dimensional data

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# number of dimensions
scalar.ndim

0

In [ ]:
# item being held within the tensor as a python int
scalar.item()

7

In [ ]:
# Vectors
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
print("The number of vector dimensions - equal to the # of parenthesis: ",vector.ndim)

The number of vector dimensions - equal to the # of parenthesis:  1


In [ ]:
print("Vector shape, equal to amount of numbers: ", vector.shape)

Vector shape, equal to amount of numbers:  torch.Size([2])


In [ ]:
# MATRIX
# shape of 2 by 2, ndim/number of dimensions of 2
# must have brackets around all pairs so its one grouping
MATRIX = torch.tensor([[8,9], [10,11]])
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor(
    [
        [
            [1,2,3],[3,6,9],[2,4,6],
            ],
        [
            [9,2,3],[36,9, 10],[21,4,69]
            ],
        ]
    )
#shape shows all dimensions for a tensor separated
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
 # making a random tensor of size(3,4)
random = torch.rand(7,2,1)
print(random)

tensor([[[0.5765],
         [0.1352]],

        [[0.7879],
         [0.5565]],

        [[0.1431],
         [0.2765]],

        [[0.2475],
         [0.9002]],

        [[0.1889],
         [0.5351]],

        [[0.5103],
         [0.3484]],

        [[0.0944],
         [0.1105]]])


In [ ]:
# squeezing, reshaping, unsqueezing tensors


In [ ]:
import torch # lets us run the nb from this cell

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# reshape must be compatible with original size in a multiplicative sense
x_reshaped = x.reshape(1, 9)
x_reshaped


tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# changing the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# stack fn

x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
 # torch.squeze
# x_reshaped.shape
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# unsqueeze - adds a single dimension to target tensor at specific dimension

unsqueeze = x_reshaped.unsqueeze(dim=1)
unsqueeze

tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [ ]:
x = torch.rand(2,3,4)
x.size()
# rearrange the dims by their arguments
torch.permute(x, (1,2,0)).size()

torch.Size([3, 4, 2])

In [ ]:
# Checking for GPU access with pytorch
import torch
torch.cuda.is_available()

True

In [ ]:
!nvidia-smi

Thu Dec 28 20:46:13 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8              10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
# setting up device agnostic code - runs regardless of what we have
# best practice
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count gpu number
torch.cuda.device_count()

1

In [ ]:
# putting tensors and models on gpu
# we want this because it's much faster

# create a tensor(default is cpu)

tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# numpy only works with cpu, keep that in mind
# for ex

tensor_cpu = tensor_on_gpu.cpu()
tensor_cpu.device

device(type='cpu')